# https://docs.docker.com/go/compose-spec-reference/
# https://github.com/docker/awesome-compose

services:
  server:
    build:
      context: .
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - sqlite-data:/data
      - type: bind
        source: ./config.toml
        target: /config.toml
volumes:
  sqlite-data:
