# https://docs.docker.com/go/compose-spec-reference/
# https://github.com/docker/awesome-compose

services:
  database:
    image: postgres:15
    restart: always
    env_file: .env
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
  cache:
    image: valkey/valkey:7.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    command: valkey-server --save 30 1
    volumes:
      - redis-data:/data
  server:
    build:
      context: .
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./config.toml
        target: /config.toml
volumes:
  postgres-data:
    name: airbot_postgres-15-data
  redis-data:
