services:
  server:
    image: ghcr.io/airforce270/airbot:release
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      database:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ./config.toml:/go/src/github.com/airforce270/airbot/config.toml
