services:
  database:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
  cache:
    image: redis:7
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    command: redis-server --save 30 1
    volumes:
      - redis-data:/data
  server:
    build:
      context: ../
      dockerfile: airbot/Dockerfile
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./config.toml:/go/src/github.com/airforce270/airbot/config.toml
volumes:
  postgres-data:
    name: airbot_postgres-15-data
  redis-data:
