services:
  database:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./config.json:/go/src/github.com/airforce270/airbot/config.json
volumes:
  postgres-data:
    name: airbot_postgres-15-data
