services:
  server:
    image: ghcr.io/airforce270/airbot:release
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      cache:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./config.toml
        target: /config.toml
