services:
  server:
    build:
      context: .
      target: final
    env_file: .env
    environment:
      - RUNNING_IN_DOCKER=true
    depends_on:
      database:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./config.toml
        target: /config.toml
