// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type BotBan struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	Platform  *string
	Channel   *string
	BannedAt  *time.Time
}

type CacheBoolItem struct {
	CreatedAt *time.Time
	UpdatedAt *time.Time
	Keyy      *string
	Value     *float64
	ExpiresAt *time.Time
}

type CacheStringItem struct {
	CreatedAt *time.Time
	UpdatedAt *time.Time
	Keyy      *string
	Value     *string
	ExpiresAt *time.Time
}

type ChannelCommandCooldown struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	Channel   *string
	Command   *string
	LastRun   *time.Time
}

type Duel struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	UserID    *int64
	TargetID  *int64
	Amount    *int64
	Pending   *float64
	Accepted  *float64
	Won       *float64
}

type GambaTransaction struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	UserID    *int64
	Game      *string
	Delta     *int64
}

type JoinedChannel struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	Platform  *string
	Channel   *string
	ChannelID *string
	Prefix    *string
	JoinedAt  *time.Time
}

type Message struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	Text      *string
	Channel   *string
	UserID    *int64
	Time      *time.Time
}

type User struct {
	ID         int64
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
	DeletedAt  *time.Time
	TwitchID   *string
	TwitchName *string
}

type UserCommandCooldown struct {
	ID        int64
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
	UserID    *int64
	Command   *string
	LastRun   *time.Time
}
