// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type BotBan struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Platform  sql.NullString
	Channel   sql.NullString
	BannedAt  sql.NullTime
}

type CacheBoolItem struct {
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Key       sql.NullString
	Value     sql.NullFloat64
	ExpiresAt sql.NullTime
}

type CacheStringItem struct {
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Key       sql.NullString
	Value     sql.NullString
	ExpiresAt sql.NullTime
}

type ChannelCommandCooldown struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Channel   sql.NullString
	Command   sql.NullString
	LastRun   sql.NullTime
}

type Duel struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	UserID    sql.NullInt64
	TargetID  sql.NullInt64
	Amount    sql.NullInt64
	Pending   sql.NullFloat64
	Accepted  sql.NullFloat64
	Won       sql.NullFloat64
}

type GambaTransaction struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	UserID    sql.NullInt64
	Game      sql.NullString
	Delta     sql.NullInt64
}

type JoinedChannel struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Platform  sql.NullString
	Channel   sql.NullString
	ChannelID sql.NullString
	Prefix    sql.NullString
	JoinedAt  sql.NullTime
}

type Message struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Text      sql.NullString
	Channel   sql.NullString
	UserID    sql.NullInt64
	Time      sql.NullTime
}

type User struct {
	ID         int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
	TwitchID   sql.NullString
	TwitchName sql.NullString
}

type UserCommandCooldown struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	UserID    sql.NullInt64
	Command   sql.NullString
	LastRun   sql.NullTime
}
