// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const createTwitchUser = `-- name: CreateTwitchUser :exec
INSERT INTO users (
  created_at, updated_at,
  twitch_id, twitch_name
) VALUES (
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
  ?, ?
)
`

type CreateTwitchUserParams struct {
	TwitchID   sql.NullString
	TwitchName sql.NullString
}

func (q *Queries) CreateTwitchUser(ctx context.Context, arg CreateTwitchUserParams) error {
	_, err := q.db.ExecContext(ctx, createTwitchUser, arg.TwitchID, arg.TwitchName)
	return err
}

const selectUserPoints = `-- name: SelectUserPoints :one
SELECT CAST(COALESCE(SUM(delta)) AS INTEGER) AS points
FROM gamba_transactions
WHERE user_id = ?
`

func (q *Queries) SelectUserPoints(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectUserPoints, userID)
	var points int64
	err := row.Scan(&points)
	return points, err
}
